#! /usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use PHPhone\PHPhone\Commands\CallCommand;
use PHPhone\PHPhone\Commands\MakeSpeechCommand;
use PHPhone\PHPhone\Commands\NewStateCommand;
use Symfony\Component\Console\Application;

(new \Dotenv\Dotenv(__DIR__))->load();

$application = new Application();

// ... register commands
//TODO: Call and dump in state
$application->add(new CallCommand());
//TODO: Create State
$application->add(new NewStateCommand());
//TODO: Create and set audio files
$application->add(new MakeSpeechCommand());

$application->run();